# Configuration for CI Pass Cracker Project

project_name: "CI Pass Cracker"
user_name: "Developer"
communication_language: "en"
implementation_artifacts: "/home/kali/project/ci_pass_cracker/ci-pass-cracker"
planning_artifacts: "/home/kali/project/ci_pass_cracker/ci-pass-cracker/planning"